menu:
  首页: /
  About: /about
  title: Fe

#author profile
profile: 
  logo: fyflying
  avatar: /img/header.jpg
  author: Fe_
  location: 杭州

social:
  twitter: https://twitter.com/fe_feng
  #facebook: "#"
  github: "https://github.com/fengye9729"
  #google: "#"
  #dribbble: '#'  
  instagram: 'https://www.instagram.com/fe_feng/'
  weibo: "https://www.weibo.com/u/3460186094"
  #rss: "#"
  #linkedin: "#"

# Content
excerpt_link: 阅读更多

favicon: /favicon.png
profileImg: /img/xiaomai.jpg
profileAbout: 等风来