menu:
  首页: /
  About: /about
  title: Fe

#author profile
profile: 
  logo: fyflying
  avatar: /img/header.jpg
  author: Fe_
  location: 杭州

social:
  #twitter: #
  #facebook: "#"
  #github: #
  #google: "#"
  #dribbble: '#'  
  #instagram: #
  #weibo: #
  #rss: "#"
  #linkedin: "#"

# Content
excerpt_link: 阅读更多

favicon: /favicon.png
profileImg: /img/xiaomai.jpg
profileAbout: 等风来